# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67acf9ae5cb4db46cb9e711b706293224058ad4c95e1ef366e9dfc1b3bd973b8b7a3fcf491cb5ce8ba91fcbc397b044f73d99a127d63e891c9b1947dcc0be11d

test:
  secret_key_base: 50aabc4d499b26831d83a6cbdc506c59d859325f1569cb9f9728baf7356ac13c65de6922652517b477571d02f214af876f63a51c086a25b30d573dfb16bd7fbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
